"""drop_activity_sessions

Revision ID: 0b1dba83b99a
Revises: d4e5f6a7b8c9
Create Date: 2026-02-28 16:18:11.327085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b1dba83b99a'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_sessions_user_date', table_name='activity_sessions')
    op.drop_index('ix_activity_sessions_user_start', table_name='activity_sessions')
    op.drop_table('activity_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('window_title', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('window_titles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activity_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='activity_sessions_pkey')
    )
    op.create_index('ix_activity_sessions_user_start', 'activity_sessions', ['user_id', 'start_time'], unique=False)
    op.create_index('ix_activity_sessions_user_date', 'activity_sessions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###
