"""add overall_productivity_score to day_summaries

Revision ID: 7c420bc77127
Revises: m3h4i5j6k7l8
Create Date: 2026-03-05 09:33:34.869488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c420bc77127'
down_revision: Union[str, None] = 'm3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_summaries', sa.Column('overall_productivity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_summaries', 'overall_productivity_score')
    # ### end Alembic commands ###
